# Generated by Django 4.0 on 2021-12-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressBookModel',
            new_name='Contact',
        ),
    ]
