# Generated by Django 4.0 on 2021-12-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_contact_options_remove_contact_complete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='home_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
